### ISSUE TITLE
產品訂購總表

### ISSUE THREAD

**Issue by hiway1001** [hiwaygithub/onlineshopping#1]
於首頁顯示產品訂購總表供現場服務員&消費者快速訂購(選完數量後按訂購直接進購物車頁面)

總表訊息包括
1. 商品類別(大項, 俗俗賣, 古早味, 新滋味)
2. 產品編號
3. 產品縮圖
4. 產品名稱
5. 產品價格
6. 數量(預設為0, 可上下增減或直接輸入數量)

點選產品縮圖或名稱後可進入該產品詳細

產品項目參考如下

https://docs.google.com/a/hiway.tw/spreadsheets/d/1NbmAbtqU20BhMggySIojf7FdCg2ewLzmWdhOxViGMHI/edit?usp=sharing

**Comment by wuboy0307** [comment]
訂購單： http://www.hiway.tw/order
12件免運 OK
發票明細 + 寄件標籤 OK
ezship OK
展場取貨 + 取貨地點 OK
