### ISSUE TITLE
啟用會員制於海味購物網

### ISSUE THREAD

**Issue by hiway1001** [hiwaygithub/onlineshopping#12]
啟用會員制於海味購物網
- 登入: e-mail or fb登入
- 註冊資訊包括 1.e-mail 2.登入密碼 3.登入密碼確認 4.姓名 5.性別 6.出生年月 7.連絡電話 8.地址
- 進購物車頁面時需檢查是否已登入會員, 若未登入導引至會員登入/註冊頁面
- 會員登入後可購買, 亦可查詢訂單資訊

**Comment by hiway1001** [comment]
修正註冊資訊包括 
  1.e-mail 
  2.登入密碼
  3.登入密碼確認
  4.姓名 
  5.連絡電話
  6.地址

**Comment by wuboy0307** [comment]
please test on staging

**Comment by wuboy0307** [comment]
fix
