### ISSUE TITLE
Add "澎湖購物,澎湖名產,澎湖特產,XO干貝醬" to the content "<meta content="" name="keywords" />" in main page

### ISSUE THREAD

**Issue by hiway1001** [hiwaygithub/onlineshopping#25]
Add "澎湖購物,澎湖名產,澎湖特產,XO干貝醬" to the content "<meta content="" name="keywords" />" in main page

**Comment by wuboy0307** [comment]
this is setting in http://www.hiway.tw/admin/general_settings/edit 
just set META KEYWORDS
