### ISSUE TITLE
購物車頁面訂單數量無法調整

### ISSUE THREAD

**Issue by hiway1001** [hiwaygithub/onlineshopping#5]
剛剛測試發現，原本購物車清單，"蚵醬下標3罐、600元"，
但是後來更改為"1罐"，價錢確不會跟著調整？(是在購物車清單直接更改數量)
(參附檔)

調整方法→

方法1：購物車清單的"數量"，直接設定成不讓消費者更改！
需要更改數量就刪除品項，重新下標。

方法2：購物車清單的數量如果調整，後面價錢就要同時跟著調整。

**Comment by wuboy0307** [comment]
done
