### ISSUE TITLE
購物車頁面, 帳單資訊全部空白沒填按結帳後, 套回購物車頁面時, 將所有資訊填入再次按結帳後仍顯示無填入資訊

### ISSUE THREAD

**Issue by hiway1001** [hiwaygithub/onlineshopping#6]
發現問題2...

消費者若第一次下單，沒有填寫姓名、電話、地址資料欄位，
會有"指示提醒"跑出！

但若依照"指示提醒"填寫完成後，到完成訂購的確認頁面，
那些"指示提醒"還會出現在上方！(參附圖)

**Comment by wuboy0307** [comment]
done
